"""base

Revision ID: ec8772c85e2b
Revises: 
Create Date: 2026-08-02 22:57:39.294737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec8772c85e2b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_schema_version')
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.alter_column('chat_id',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('global_messages', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.TEXT(),
               type_=sa.Date(),
               existing_nullable=False)

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.TEXT(),
               type_=sa.Date(),
               existing_nullable=True)

    with op.batch_alter_table('message_attachments', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('p2p_messages', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.TEXT(),
               type_=sa.Date(),
               existing_nullable=False)

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.alter_column('jti',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('expires_at',
               existing_type=sa.TEXT(),
               type_=sa.Date(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.alter_column('expires_at',
               existing_type=sa.Date(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('jti',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('p2p_messages', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.Date(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('message_attachments', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.Date(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('global_messages', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.Date(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('chat_id',
               existing_type=sa.TEXT(),
               nullable=True)

    op.create_table('_schema_version',
    sa.Column('version', sa.INTEGER(), nullable=False)
    )
    # ### end Alembic commands ###
