version: "3.9"

services:
  voice:
    build: .
    container_name: voice-chat
    ports:
      - "443:8080"
    restart: unless-stopped

  turn:
    image: instrumentisto/coturn
    container_name: coturn
    restart: unless-stopped

    network_mode: host

    command: >
      -n
      --log-file=stdout

      --lt-cred-mech
      --fingerprint

      --user=webrtc:webrtc123
      --realm=webrtc.local

      --listening-port=3478
      --tls-listening-port=5349

      --min-port=50000
      --max-port=50100

      --external-ip=185.103.252.46